nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.2.cjs

logFilters:
  # Hide messages "The xyz architecture is incompatible with this module, link skipped."
  - code: "YN0076"
    level: discard
